From compcert Require Import Values Clight Memory Ctypes AST Globalenvs Integers.
From compcert Require Import -(notations) Maps.
Import PTree.
From VST.concurrency.openmp_sem Require Import permissions HybridMachineSig HybridMachine finThreadPool clight_evsem_fun notations team_dyn Clight_evsem.
Import HybridMachineSig.
Import ThreadPool. Import FinPool.
From VST.concurrency.openmp_sem Require Import parallel_for_omp mem_equiv.
From stdpp Require Import base tactics option.
From Coq Require Import Relations.Relation_Operators Numbers.BinNums.
From mathcomp.ssreflect Require Import ssreflect.
Require Import Coq.Program.Equality.

From VST.concurrency.openmp_sem Require Import DryHybridMachineInst exec_tac.
Set Bullet Behavior "Strict Subproofs".

(* FIXME remove when done *)
Set Nested Proofs Allowed.
Arguments Mem.storev: simpl never.
Arguments Mem.alloc: simpl never.
(* Arguments Mem.mem_access : simpl never. *)
Arguments int_perm : simpl never.

#[global] Instance aa : Prog := { cprog := parallel_for_omp.prog }.

Theorem parallel_for_exec :
    ∀ os1, init_Ostate os1 ->
    os1.schd = [0;0;0] ->
    ∃ os2, OpenMP_steps os1 os2.
Proof.
    intros os1 H HU.
    (* get initial state *)
    unfold init_Ostate in H.
    destruct H as (m0&b&tp&U&Hm0&Hb&Hinit&Hos).
    simpl in Hinit. unfold DryHybridMachine.init_mach in Hinit.
    destruct Hinit as (c&Hc&Htp). simpl in Hc. destruct_match in Hc. clear e.
    destruct Hc as [Hc _]. destruct_match in Hc eqn:Hf.
    inv' Hc.
    rewrite -> Hos in *.
    simpl in HU. subst.
    match goal with
    | |- ∃ _, OpenMP_steps (?_U, ?_tr, ?_tp, ?_ttree, _) _ =>
        set (U' := _U); set (tr := _tr); set (tp := _tp); set (ttree := _ttree)
    end.
    
    rewrite /Genv.find_symbol /Genv.genv_symb in Hb.
    unfold PTree.get in Hb.
    simpl in Hb.
    injection Hb as <-.
    rewrite /Genv.find_funct_ptr /= in Hf.
    injection Hf as <-.

    (* compute m *)

    rewrite /Genv.init_mem /= in Hm0.
    rewrite /Mem.drop_perm in Hm0.
    destruct_match in Hm0 eqn:Hm0_0.
    (* Transparent Mem.alloc. rewrite /Mem.alloc in Hm0_0. Opaque Mem.alloc. *)
    simpl in Hm0_0. inv Hm0_0.
    simpl in Hm0.
    destruct_match in Hm0 eqn:Hm1. injection Hm0 as <-.

    (* simplify m1 *)
    set_mem_as m1.
  
    (* extract intermediate memories.
      Naming convention: mi is the memory when taking the `i`th step;
      after m(i-1), the intermediate memories are mi_j:
        m(i-1) -> mi_0 -> mi_1 -> mi_2 -> ... mi;
      Hmi_j are hyps about mi_j.
       *)
    destruct (Mem.alloc Mem.empty Z0 (Zpos xH)) as [m1_0 b1_0] eqn:Hm1_0.
    (* replace b1_0 with concrete value *)
    apply Mem.alloc_result in Hm1_0 as Hb1_0; subst b1_0.
    apply Mem.nextblock_alloc in Hm1_0 as Hm1_nextblock.

    (* simplify tp *)
    unfold getCurPerm, Mem.mem_access in tp; simpl in tp.

    (* take steps *)
    eexists.

    (** take 1st step *)
    pose tid:nat:=0.
    (* technically it would be equivalent to not instantiate this evar and just
       replace m' in Ostep_step_dry_tac with '_', but for some reason that makes
       thread_step_tac_partial generates a huge proof term for the memory and
       slows computation down drastically.  *)
    evar (m2:mem).

    thread_step_1_tac_partial 0 tp1 m2.
    {
      apply evstep_fun_correct.
      rewrite /cl_evstep_fun /m2 /=.
      destruct_match eqn: Hm3.
      destruct_match eqn: Hm4.
      simpl.
      inv Hm3. inv Hm4. done.
    }
    { done. }
    simplify_mem m2.
    destruct (Mem.alloc m1 Z0 (Zpos (xO (xO xH)))) as [m2_0 b2_0] eqn: Hm2_0.
    apply Mem.alloc_result in Hm2_0 as Hb2_0; subst b2_0.
    destruct (Mem.alloc m2_0 Z0 (Zpos (xO (xO xH)))) as [m2_1 b2_1] eqn: Hm2_1.
    apply Mem.alloc_result in Hm2_1 as Hb2_1; subst b2_1.

    thread_step_clean_up cnt Hcompat tp tp2.
    subst m2.
    
    (** take 2nd step *)
    thread_step_1_tac 0 tp3.

    (** take 3rd step *)
    thread_step_1_tac 0 tp4.

    (* this magical term m3 is obtained by first running
        evar (m5: mem).
        thread_step_tac_partial 0 tp4 m5.
        ...
      which computes the new memory. We probably cannot do it inside the first
      subgoal generated by thread_step_tac_partial due to evar instantiation
      limitations. *)
    assert (∃ m3, Some m3 = (Mem.storev Mint32 m2_1 (Vptr (Mem.nextblock m1_0) Ptrofs.zero) (Vint (Int.repr Z0)))) as [m3 Hm3].
    { 
      Transparent Mem.store. rewrite /Mem.storev /Mem.store /=. Opaque Mem.store.
      destruct (Mem.valid_access_dec _ _ _ _ _) as [|not_writable]; [ eexists; done | contradict not_writable].

      eapply Mem.valid_access_alloc_other; eauto.
      apply Mem.valid_access_freeable_any.
      apply (Mem.valid_access_alloc_same _ _ _ _ _ Hm2_0); try done.
      rewrite /BinInt.Z.divide. exists Z0. done.
    }

    evar (m5: mem).
    (** take 4th step *)
    thread_step_1_tac_partial 0 tp4 m5.
    1: {
      apply evstep_fun_correct.
      rewrite /cl_evstep_fun /=.
      destruct decide; try done. simpl.
      rewrite Cop.cast_val_casted; last (by constructor); simpl.
      rewrite -Hm3 /m5 //=.
    }
    1: { done. }
    subst m5.
    thread_step_clean_up cnt Hcompat tp4 tp5.

    (* take 5th step *)
    thread_step_1_tac 0 tp5.

    (* take 6th step *)
    thread_step_1_tac 0 tp6.
    
    (* take 7th step: suspend_step_pragma
       TODO automate this *)
    assert_cnt 0 cnt7 Hcompat7.
        
    eapply (rt1n_trans Ostate Ostep _ (_, _, _, ttree, diluteMem _)).
    {
        rewrite /Ostep /MachStep /=.
        eapply suspend_step_pragma; try done.
        eapply (SuspendThreadPragma _ _ _ _ _ _ _ _ Hcompat7).
        { rewrite vector.vlookup_lookup //=. }
        { simpl. unfold DryHybridMachine.install_perm.
          rewrite (@restrPermMap_eq m3 (proj1 (Hcompat7 0 _))) //. }
        { done. }
        { tp_inv_tac_one. }
        simpl.
        done.
    }
    thread_step_clean_up cnt7 Hcompat7 tp6 tp8.
        
    (* take 8th step: step_parallel *)
    assert_cnt 0 cnt8 Hcompat8.
    
    assert (Hres: res = (access_map * access_map)%type) by done.
    pose cur_m3 := (getCurPerm m3).
    pose perm8 := (cur_m3, empty_map).

    pose curPerm_m1 := (PMap.map (λ (entry : Z → perm_kind → option permission) (ofs : Z),
                        entry ofs Cur) (Mem.mem_access m1)).
    assert (curPerm_m1_unit: permMapJoin curPerm_m1 curPerm_m1 curPerm_m1).
    {
      (* by case-analysis on block *)
      rewrite /permMapJoin => _b _ofs.
      rewrite /curPerm_m1 /m1 /=.
      rewrite PMap.gmap /=.
      destruct (decide (_b = xH)) as [H_b|H_b].
      - rewrite H_b PMap.gss /=.
        destruct (Coqlib.proj_sumbool (Coqlib.zle Z0 _ofs) && Coqlib.proj_sumbool (Coqlib.zlt _ofs (Zpos xH))) eqn:H_ofs.
        + constructor.
        + Transparent Mem.alloc. injection Hm1_0 as <-. simpl. Opaque Mem.alloc.
          rewrite /m1_mem_access /= PMap.gss H_ofs.
          constructor.
      - rewrite PMap.gso //.
        Transparent Mem.alloc. injection Hm1_0 as <-. simpl. Opaque Mem.alloc.
        rewrite /m1_mem_access /= PMap.gso //.
        rewrite /PMap.init /PMap.get /=.
        constructor.
    }

    (* perm8 is divided to perm8_1 and perm8_2 (w.r.t. permMapJoinPair); more specifically, the Freeable locations are divided into Readables,
       and curPerm_m1 is not divided because it is a unit of the permMapJoin relation (it only contains Nonempty permission of a location that
       we do no care ). *)

    set (b_count := (BinPos.Pos.succ (Mem.nextblock m1_0))).
    set (b_i := (Mem.nextblock m1_0)).
    pose perm8_1 : (access_map * access_map) := (PMap.set b_count (int_perm $ Some Readable)
                      (PMap.set b_i (int_perm $ Some Readable)
                        curPerm_m1),
                     empty_map).
    pose perm8_2 : (access_map * access_map) := (PMap.set b_count (int_perm $ Some Readable)
                      (PMap.set b_i (int_perm $ Some Readable)
                        curPerm_m1),
                     empty_map).
    pose perms8 := [perm8_1; perm8_2].

    assert (perm8_1 ∈ perms8) by repeat constructor.
    assert (perm8_2 ∈ perms8) by repeat constructor.
    
    assert (Hcur_m3 : cur_m3 = (PMap.set b_count (int_perm $ Some Freeable) $
                                          PMap.set b_i (int_perm $ Some Freeable) curPerm_m1)).
    {
      rewrite /cur_m3 /getCurPerm /=.
      apply storev_mem_access in Hm3 as ->.
      inv Hm2_1. inv Hm2_0.
      remember m1 as m1' eqn:Hm1'.
      Transparent Mem.alloc. simpl. Opaque Mem.alloc. subst m1'.
      rewrite !getCurPerm_set /curPerm_m1  /b_count /b_i //.
    }

    assert (Hperms8_lemma : permMapJoinPair perm8_1 perm8_2 perm8).
    {
      clear -Hcur_m3 curPerm_m1_unit.
      rewrite /permMapJoinPair /=.
      split; [|apply permMapJoin_empty].
      rewrite Hcur_m3.
      apply permMapJoin_split_perm;[constructor|].
      apply permMapJoin_split_perm;[constructor|].
      apply curPerm_m1_unit.
    }

    assert (Hperms8 : permMapJoin_list perms8 perm8).
    {
      clear -Hperms8_lemma.
      rewrite /permMapJoinPair /=.
      econstructor 2.
      { apply permMapJoinPair_empty. }
      econstructor 2.
      { apply Hperms8_lemma. }
      constructor.
    }

    eapply (rt1n_trans Ostate Ostep _ (_, _, _:ThreadPool.t, _, diluteMem _)).
    {
        (* take a suspend_step *)
        rewrite /Ostep /MachStep /=.
        eapply pragma_step.
        { done. }
        eapply (step_parallel cnt8 Hcompat8 _ _ _ _ _ _ _ _ m3 _ 2 _ _ _ _ _ _ perm8 perms8).
        { tp_inv_tac_one. }
        { apply (restrPermMap_eq (proj1 (Hcompat8 0 cnt8))). }
        { simpl. done. }
        { simpl. done. }
        { lia. }
        { done. }
        { apply Hperms8. }
        { done. }
        { done. }
        { done. }
        { done. }
        { done. }
        { done. }
        { done. }
        {
          simpl.
          
          (* simplify spawn_team *)
          rewrite /spawn_team /update_tid /stree_update /tz_update tz_lookup_unfold_eq /= /is_tid /=.
          case_bool_decide; [|lia].

          (* simplfiy RecordSet.set and to_tree *)
          rewrite /to_stree /RecordSet.set /=.
          done.
        }
      }
    thread_step_clean_up tp8 cnt8 Hcompat8 tp9.

    thread_step_2_tac 0 tp10 Hperms8.
    eapply (rt1n_trans Ostate Ostep _ (_, _, _, _, diluteMem _)).
    {
        rewrite /Ostep /MachStep /=.
        eapply suspend_step_pragma; try done.
        eapply (SuspendThreadPragma _ _ _ _ _ _ _ _ _).
        { rewrite vector.vlookup_lookup //=. }
        { simpl. unfold DryHybridMachine.install_perm.
          rewrite restrPermMap_eq. done. }
        { done. }
        { tp_inv_tac_multiple.
          simpl.
          (* FIXME rewrite getCur_restr with permMapJoin_list_proper *)
          (* rewrite getCur_restr. *)
          admit.
        }
        simpl.
        done.
    }

    
    (* tid 0 take step_omp_for *)
    assert_cnt_2_tac 0 Hperms8 cnt10 Hcompat10.
    eapply (rt1n_trans Ostate Ostep _ (_, _, _, ttree, diluteMem _)).
    {
        rewrite /Ostep /MachStep /=.
        eapply pragma_step; first done.
        eapply (step_for cnt10 Hcompat10).
        { simpl. done. }
        { tp_inv_tac_one. }
        { apply (restrPermMap_eq (proj1 (Hcompat10 0 cnt10))). }
        { simpl. done. }
        { simpl. done. }
        { lia. }
        { done. }
        { apply Hperms8
        eapply (SuspendThreadPragma _ _ _ _ _ _ _ _ Hcompat7).
        { rewrite vector.vlookup_lookup //=. }
        { simpl. unfold DryHybridMachine.install_perm.
          rewrite (@restrPermMap_eq m3 (proj1 (Hcompat7 0 _))) //. }
        { done. }
        { tp_inv_tac_one. }
        simpl.
        done.
    }
               
              
Admitted.