(** * Sample AST input to the ClightOMP compiler
    
  The contents up to [prog] is generated by clightgen; Spragma and pragma info
  are added manually (also the lifting to stmtT) for now. *)
From Coq Require Import String List ZArith.
From compcert Require Import Coqlib Integers Floats Values AST Ctypes Cop Csyntax Csyntaxdefs.
Import Csyntaxdefs.CsyntaxNotations.
Local Open Scope Z_scope.
Local Open Scope string_scope.
Local Open Scope csyntax_scope.

Module Info.
  Definition version := "3.14".
  Definition build_number := "".
  Definition build_tag := "".
  Definition build_branch := "".
  Definition arch := "aarch64".
  Definition model := "default".
  Definition abi := "apple".
  Definition bitsize := 64.
  Definition big_endian := false.
  Definition source_file := "cmplr_src1.c".
End Info.

Definition ___stringlit_1 : ident := $"__stringlit_1".
Definition _i : ident := $"i".
Definition _j : ident := $"j".
Definition _k : ident := $"k".
Definition _l : ident := $"l".
Definition _main : ident := $"main".
Definition _printf : ident := $"printf".

Definition v___stringlit_1 := {|
  gvar_info := (tarray tschar 24);
  gvar_init := (Init_int8 (Int.repr 105) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 61) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 37) :: Init_int8 (Int.repr 100) ::
                Init_int8 (Int.repr 44) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 106) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 61) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 37) :: Init_int8 (Int.repr 100) ::
                Init_int8 (Int.repr 44) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 107) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 61) :: Init_int8 (Int.repr 32) ::
                Init_int8 (Int.repr 37) :: Init_int8 (Int.repr 100) ::
                Init_int8 (Int.repr 10) :: Init_int8 (Int.repr 0) :: nil);
  gvar_readonly := true;
  gvar_volatile := false
|}.

Definition f_main := {|
  fn_return := tint;
  fn_callconv := cc_default;
  fn_params := nil;
  fn_vars := ((_i, tint) :: (_j, tint) :: (_k, tint) :: (_l, tint) :: nil);
  fn_body :=
    (Ssequence
      (Ssequence
        (Sdo (Eassign (Evar _i tint) (Eval (Vint (Int.repr 0)) tint) tint))
        (Ssequence
          (Sdo (Eassign (Evar _j tint) (Eval (Vint (Int.repr 0)) tint) tint))
          (Ssequence
            (Sdo (Eassign (Evar _k tint) (Eval (Vint (Int.repr 0)) tint) tint))
            (Ssequence
              (Ssequence
                (Sdo (Epostincr Incr (Evar _i tint) tint))
                (Ssequence
                  (Sdo (Eassign (Evar _j tint) (Eval (Vint (Int.repr 1)) tint)
                        tint))
                  (Ssequence
                    (Sdo (Eassign (Evar _k tint) (Eval (Vint (Int.repr 1)) tint)
                          tint))
                    (Sdo (Eassign (Evar _l tint) (Eval (Vint (Int.repr 0)) tint)
                          tint)))))
              (Sdo (Ecall
                    (Evalof
                      (Evar _printf (Tfunction (Tcons (tptr tschar) Tnil) tint
                                      {|cc_vararg:=(Some 1); cc_unproto:=false; cc_structret:=false|}))
                      (Tfunction (Tcons (tptr tschar) Tnil) tint
                        {|cc_vararg:=(Some 1); cc_unproto:=false; cc_structret:=false|}))
                    (Econs
                      (Evalof (Evar ___stringlit_1 (tarray tschar 24))
                        (tarray tschar 24))
                      (Econs (Evalof (Evar _i tint) tint)
                        (Econs (Evalof (Evar _j tint) tint)
                          (Econs (Evalof (Evar _k tint) tint) Enil)))) tint))))))
      (Sreturn (Some (Eval (Vint (Int.repr 0)) tint))))
  |}.

Definition composites : list composite_definition :=
nil.

Definition global_definitions : list (ident * globdef fundef type) :=
(
 (_printf,
   Gfun(External (EF_external "printf"
                   (mksignature (AST.Tlong :: nil) AST.Tint
                     {|cc_vararg:=(Some 1); cc_unproto:=false; cc_structret:=false|}))
     (Tcons (tptr tschar) Tnil) tint
     {|cc_vararg:=(Some 1); cc_unproto:=false; cc_structret:=false|})) ::
 (_main, Gfun(Internal f_main)) :: nil).

Definition public_idents : list ident :=
(_main :: _printf :: 
 nil).

Definition prog : Csyntax.program := 
  mkprogram composites global_definitions public_idents _main Logic.I.


(* The above are generated by `clightgen -Csyntax`. Developments start here. *)
From compcert Require Import Clight SimplExpr.
From omp_compiler Require Import ClightT.
Import ListNotations.

(* step 1: apply the SimplExpr pass but not the SimplLocal pass, so everything
  is still on heap *)
Definition prog_clight_no_pragma' : Errors.res Clight.program :=
  transl_program prog.

(* print clight ast, copy the result as f_main_clight for later use *)
Example print_f_main_clight : True.
  let p := eval cbn in prog_clight_no_pragma' in
  match p with
  | Errors.OK ?p => idtac p end.
  Abort.

Definition spar_body : statement :=
  Ssequence
    (Ssequence Sskip
      (Sassign (Evar _i tint)
          (Ebinop Oadd 
            (Evar _i tint)
            (Econst_int Int.one type_int32s)
            (Tint I32 Signed noattr))))
    (Ssequence
      (Ssequence Sskip
          (Sassign (Evar _j tint)
            (Econst_int (Int.repr 1) tint)))
      ((Ssequence 
          (Ssequence Sskip (Sassign (Evar _k tint) (Econst_int (Int.repr 1) tint)))
          (Ssequence Sskip (Sassign (Evar _l tint) (Econst_int (Int.repr 0) tint)))
                                ))).

Definition f_main_clight :=
  {|
    fn_return := tint;
    fn_callconv := cc_default;
    fn_params := nil;
    fn_vars := (_i, tint) :: (_j, tint) :: (_k, tint) :: (_l, tint) :: nil;
    fn_temps := nil;
    fn_body :=
      Ssequence
        (Ssequence
           (Ssequence Sskip
              (Sassign (Evar _i tint)
                 (Econst_int (Int.repr 0) tint)))
           (Ssequence
              (Ssequence Sskip
                 (Sassign (Evar _j tint)
                    (Econst_int (Int.repr 0) tint)))
              (Ssequence
                 (Ssequence Sskip
                    (Sassign (Evar _k tint)
                       (Econst_int (Int.repr 0) tint)))
                 (Ssequence
                    spar_body
                    (Ssequence Sskip
                       (Scall None
                          (Evar _printf
                             (Tfunction 
                                (Tcons (tptr tschar) Tnil) tint
                                {|
                                  cc_vararg := Some 1;
                                  cc_unproto := false;
                                  cc_structret := false
                                |}))
                          (Evar ___stringlit_1 (tarray tschar 24)
                           :: Evar _i tint
                              :: Evar _j tint
                                 :: Evar _k tint :: nil)))))))
        (Ssequence Sskip
           (Sreturn (Some (Econst_int (Int.repr 0) tint))))
  |}.

Definition prog_clight_no_pragma :=
  {|
    prog_defs :=
    (_printf,
      Gfun
        (External
            (EF_external "printf"
              {|
                sig_args := AST.Tlong :: nil;
                sig_res := AST.Tint;
                sig_cc :=
                  {|
                    cc_vararg := Some 1;
                    cc_unproto := false;
                    cc_structret := false
                  |}
              |}) (Tcons (tptr tschar) Tnil) tint
            {|
              cc_vararg := Some 1; cc_unproto := false; cc_structret := false
            |}))
      :: (_main, Gfun (Internal f_main_clight))
                :: nil;
    prog_public := public_idents;
    prog_main := _main;
    prog_types := composites;
    prog_comp_env := Maps.PTree.empty composite;
    prog_comp_env_eq := eq_refl
  |}.

(* san check *)
Lemma f_main_clight_eq :
  Errors.OK prog_clight_no_pragma = prog_clight_no_pragma'.
Proof. reflexivity. Qed.

(* step 2 : add the missing [Spragma]s back to f_main_clight *)
Definition f_main_omp : function :=
  {|
    fn_return := tint;
    fn_callconv := cc_default;
    fn_params := nil;
    fn_vars := (_i, tint) :: (_j, tint) :: (_k, tint) :: nil;
    fn_temps := nil;
    fn_body :=
      Ssequence
        (Ssequence
           (Ssequence Sskip
              (Sassign (Evar _i tint)
                 (Econst_int (Int.repr 0) tint)))
           (Ssequence
              (Ssequence Sskip
                 (Sassign (Evar _j tint)
                    (Econst_int (Int.repr 0) tint)))
              (Ssequence
                 (Ssequence Sskip
                    (Sassign (Evar _k tint)
                       (Econst_int (Int.repr 0) tint)))
                 (Ssequence Sskip
                    (Ssequence 
                      (Spragma 0 (OMPParallel 2 (PrivClause (_j::nil)) (PrivClause nil) ((RedClause RedIdPlus (_k::nil))::nil))
                        spar_body)
                      (Scall None
                          (Evar _printf
                            (Tfunction 
                                (Tcons (tptr tschar) Tnil) tint
                                {|
                                  cc_vararg := Some 1;
                                  cc_unproto := false;
                                  cc_structret := false
                                |}))
                          (Evar ___stringlit_1 (tarray tschar 24)
                          :: Evar _i tint
                              :: Evar _j tint
                                :: Evar _k tint :: nil)))))))
        (Ssequence Sskip
           (Sreturn (Some (Econst_int (Int.repr 0) tint))))
  |}.

Definition prog_clight : Clight.program :=
  {|
    prog_defs :=
      (_printf,
        Gfun
          (External
              (EF_external "printf"
                {|
                  sig_args := AST.Tlong :: nil;
                  sig_res := AST.Tint;
                  sig_cc :=
                    {|
                      cc_vararg := Some 1;
                      cc_unproto := false;
                      cc_structret := false
                    |}
                |}) (Tcons (tptr tschar) Tnil) tint
              {|
                cc_vararg := Some 1; cc_unproto := false; cc_structret := false
              |}))
        :: (_main, Gfun (Internal f_main_omp))
                  :: nil;
    prog_public := public_idents;
    prog_main := _main;
    prog_types := composites;
    prog_comp_env := Maps.PTree.empty composite;
    prog_comp_env_eq := eq_refl
  |}.

(* step 3: add pragma_info to every Spragma. To store them, stmt has to be
  lifted to statementT. TODO This is done manually for now. *)
Definition pi : pragma_info := mk_pragma_info [(_i, tint)] [(_j, tint)] [(_k, tint)] [(_l, tint)].

Definition spar_body_T : statementT :=
  SsequenceT
    (SsequenceT SskipT
      (SassignT (Evar _i tint)
          (Ebinop Oadd 
            (Evar _i tint)
            (Econst_int Int.one type_int32s)
            (Tint I32 Signed noattr))))
    (SsequenceT
      (SsequenceT SskipT
          (SassignT (Evar _j tint)
            (Econst_int (Int.repr 1) tint)))
      (SsequenceT SskipT
          (SassignT (Evar _k tint)
            (Econst_int (Int.repr 1) tint)))).

Definition f_main_clightT : functionT :=
  {|
    fn_returnT := tint;
    fn_callconvT := cc_default;
    fn_paramsT := nil;
    fn_varsT := ((_i, tint) :: (_j, tint) :: (_k, tint) :: (_l, tint) :: nil);
    fn_tempsT := nil;
    fn_bodyT :=
      (SsequenceT
        (SsequenceT
          (SassignT (Evar _i tint) (Econst_int (Int.repr 0) tint)) (*TODO: write pass to replace Sset with Sassign and also to move fn_temps to fn_vars*)
          (SsequenceT
            (SassignT (Evar _j tint) (Econst_int (Int.repr 0) tint))
            (SsequenceT
              (SassignT (Evar _k tint) (Econst_int (Int.repr 0) tint))
              (SsequenceT
                (SsequenceT
                  (SassignT (Evar _i tint)
                    (Ebinop Oadd (Evar _i tint) (Econst_int (Int.repr 1) tint)
                      tint))
                  (SsequenceT
                    (SsetT _j (Econst_int (Int.repr 1) tint))
                    (SsequenceT
                      (SassignT (Evar _j tint) (Econst_int (Int.repr 1) tint))
                      (SassignT (Evar _l tint)  (Econst_int (Int.repr 0) tint)))))
                (SsequenceT (SpragmaT pi 0 (OMPParallel 2 (PrivClause (_j::nil)) (PrivClause nil) ((RedClause RedIdPlus (_k::nil))::nil))
                        spar_body_T)
                (ScallT None
                  (Evar _printf (Tfunction (Tcons (tptr tschar) Tnil) tint
                                  {|cc_vararg:=(Some 1); cc_unproto:=false; cc_structret:=false|}))
                  ((Evar ___stringlit_1 (tarray tschar 24)) ::
                  (Evar _i tint) :: (Evar _j tint) ::
                  (Evar _k tint) :: nil)))))))
        (SreturnT (Some (Econst_int (Int.repr 0) tint))))
  |}.

Definition prog_clightT : ClightT.program :=
  {|
    prog_defs :=
      (_printf,
        Gfun
          (External
              (EF_external "printf"
                {|
                  sig_args := AST.Tlong :: nil;
                  sig_res := AST.Tint;
                  sig_cc :=
                    {|
                      cc_vararg := Some 1;
                      cc_unproto := false;
                      cc_structret := false
                    |}
                |}) (Tcons (tptr tschar) Tnil) tint
              {|
                cc_vararg := Some 1; cc_unproto := false; cc_structret := false
              |}))
        :: (_main, Gfun (Internal f_main_clightT))
                  :: nil;
    prog_public := public_idents;
    prog_main := _main;
    prog_types := composites;
    prog_comp_env := Maps.PTree.empty composite;
    prog_comp_env_eq := eq_refl
  |}.